version: '3'

services:
  user.data:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - user_data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_net

  sql.data:
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: always
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql
    networks:
      - sql_data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pass@word

  applicants.api:
    image: justdams/elec-applicants
    restart: always
    ports:
      - 8081:80
    networks:
      - rabbitmq_net
      - sql_data
    depends_on:
      - rabbitmq
      - sql.data
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;
      - HostRabbitmq=rabbitmq

  jobs.api:
    image: justdams/elec-jobs
    container_name: service-api-jobs
    restart: always
    ports:
      - 8083:80
    networks:
      - rabbitmq_net
      - sql_data
      - web
    depends_on:
      - rabbitmq
      - sql.data
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
      - HostRabbitmq=rabbitmq

  identity.api:
    image: justdams/elec-identity
    container_name: service-api-identity
    restart: always
    ports:
      - 8084:80
    networks:
      - rabbitmq_net
      - user_data
      - sql_data
      - web
    depends_on:
      - user.data
      - rabbitmq
      - sql.data
    environment:
      - RedisHost=user.data:6379
      - HostRabbitmq=rabbitmq

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    ports:
      - 80:80
    depends_on:
      - user.data
      - rabbitmq
      - sql.data
      - applicants.api
      - jobs.api
      - identity.api
    networks:
      - web

volumes:
  mssql:


networks:
  user_data:
  rabbitmq_net:
  sql_data:
  web:
